In [375]:
import numpy as np
import pandas as pd

In [376]:
dataset = pd.read_excel("DataSet.xlsx")
dataset.head(10)

qd  gos  training2  creadit3  capital  gender  experience  age  education
0   0    0          1         1      1.5       0           8   45          5
1   0    0          1         0      0.3       0           1   29         12
2   0    0          0         0      9.0       1           5   35         18
3   1    0          1         0      9.5       1          12   56         10
4   0    0          0         0     13.0       1           8   50         32
5   0    1          0         1      5.0       0           8   47         16
6   0    0          0         0      2.0       1          12   58         16
7   0    0          1         1      0.3       0           3   34          8
8   0    0          0         0      4.0       0           5   51         12
9   0    0          0         1      1.5       1           3   35          0

In [377]:
corr = dataset.corr()
corr.style.background_gradient(cmap='coolwarm')

In [378]:
display(dataset[["qd","gos","training2","creadit3"]].apply(pd.Series.value_counts))

qd  gos  training2  creadit3
0  302  356        153       291
1  102   48        251       113

In [379]:
# input
x = dataset.iloc[:, [1,2,3,4,5,6,7,8]].values

# output
y = dataset.iloc[:,0].values

In [380]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [381]:
from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# X_train = sc_x.fit_transform(X_train) 
# X_test = sc_x.transform(X_test)
  
print (X_train[0:14, :])

[[ 0.    0.    1.    0.52  1.    2.   33.   13.  ]
 [ 0.    0.    0.    1.    1.    3.   26.    6.  ]
 [ 0.    1.    0.    8.    1.    7.   48.   20.  ]
 [ 0.    1.    1.    4.    0.    8.   48.    3.  ]
 [ 0.    1.    0.    6.    0.    2.   46.    2.  ]
 [ 0.    0.    1.    2.    0.    1.   35.    9.  ]
 [ 0.    1.    0.    3.    0.    8.   35.    5.  ]
 [ 0.    1.    0.    1.    0.    3.   31.    5.  ]
 [ 0.    1.    1.    3.    0.    6.   44.   13.  ]
 [ 0.    1.    1.    0.92  1.    7.   43.   13.  ]
 [ 0.    0.    0.    7.    1.    9.   49.   20.  ]
 [ 1.    1.    0.    1.    1.   10.   56.    3.  ]
 [ 0.    0.    0.    8.    0.    6.   44.    8.  ]
 [ 0.    1.    1.    2.    0.    1.   30.   12.  ]]


In [382]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 6, fit_intercept = 1)
classifier.fit(X_train, y_train)

LogisticRegression(fit_intercept=1, random_state=6)

In [383]:
import statsmodels.api as sm
logit_model = sm.Logit(y_train,X_train)
result = logit_model.fit()
display(result.summary())

Optimization terminated successfully.
         Current function value: 0.518965
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  323
Model:                          Logit   Df Residuals:                      315
Method:                           MLE   Df Model:                            7
Date:                Fri, 14 Oct 2022   Pseudo R-squ.:                  0.1045
Time:                        18:29:41   Log-Likelihood:                -167.63
converged:                       True   LL-Null:                       -187.18
Covariance Type:            nonrobust   LLR p-value:                 1.867e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             1.2921      0.401      3.219      0.001       0.505       2.079
x2             0.8936      0.283      3.153      0.002       0.338       1.449
x3             0.5638      0.294      1.919      0.055      -0.012       1.140
x4             0.0470      0.036      1.296      0.195      -0.024       0.118
x5            -0.0007      0.267     -0.003      0.998      -0.524       0.523
x6             0.3495      0.070      5.001      0.000       0.213       0.486
x7            -0.1094      0.017     -6.366      0.000      -0.143      -0.076
x8             0.0364      0.023      1.574      0.115      -0.009       0.082
==============================================================================
"""

In [384]:
ResultList = []
for i in X_test:
    predict = result.predict(i)
    if(predict >= 0.5):
        ResultList.append(1)
    else:
        ResultList.append(0)
display(np.array(ResultList))

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [385]:
classifier.score(X_train, y_train)

0.7647058823529411

In [386]:
classifier.score(X_test, y_test)

0.8024691358024691

In [387]:
classifier.coef_

array([[ 1.09147938,  1.05397987,  0.63225572,  0.06027286,  0.1163442 ,
         0.21889654, -0.04561413,  0.04517245]])

In [388]:
classifier.intercept_

array([-2.31230256])

In [389]:
y_pred = classifier.predict(X_test)

In [390]:
from sklearn.metrics import confusion_matrix
qd = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", qd)

Confusion Matrix : 
 [[61  4]
 [12  4]]


In [391]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8024691358024691


In [392]:
qdtest = qd1.iloc[:, [1,2,3,4,5,6,7,8]].values
qdtest = sc_x.fit_transform(qdtest) 

In [393]:
#Tranform model
classifier.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
qd1 = dataset[dataset["qd"] == 1]
qd1.tail(10)

qd  gos  training2  creadit3  capital  gender  experience  age  education
381   1    1          0         1    12.00       1           8   45         18
383   1    0          1         0     2.30       0          12   55          8
385   1    0          1         0    10.00       1          12   59         20
388   1    0          1         0     3.00       1           5   37         12
389   1    0          1         0     3.00       0           4   37         12
390   1    1          1         1     7.00       0          11   55         20
391   1    1          1         1     9.00       0           9   52          6
392   1    1          1         0     2.00       0           2   28         12
397   1    0          1         1     6.00       1          11   50         12
403   1    0          1         1     0.85       1           3   27         12

In [404]:
import math
def PredictPro(gos, training, credit, experience, intercept):
    gosPara = classifier.coef_[0][0]
    trainingPara = classifier.coef_[0][1]
    creditPara = classifier.coef_[0][2]
    experiencePara = classifier.coef_[0][5]
    logarit = intercept + gosPara*gos - trainingPara*training + \
    creditPara*credit + experiencePara*experience
    Decision = 1/(1+math.exp(-logarit))
    
    if(Decision >= 0.5):
        return 1
    else:
        return 0


print(PredictPro(1,0,1,8, classifier.intercept_))

1
