In [6]:
import numpy as np
import pandas as pd

In [13]:
dataset = pd.read_excel("DataSet.xlsx")
dataset.head(10)

qd  gos  training2  creadit3  capital  gender  experience  age  education
0   0    0          1         1      1.5       0           8   45          5
1   0    0          1         0      0.3       0           1   29         12
2   0    0          0         0      9.0       1           5   35         18
3   1    0          1         0      9.5       1          12   56         10
4   0    0          0         0     13.0       1           8   50         32
5   0    1          0         1      5.0       0           8   47         16
6   0    0          0         0      2.0       1          12   58         16
7   0    0          1         1      0.3       0           3   34          8
8   0    0          0         0      4.0       0           5   51         12
9   0    0          0         1      1.5       1           3   35          0

In [333]:
qd1 = dataset[dataset.qd==0]

In [280]:
display(dataset[["qd","gos","training2","creadit3"]].apply(pd.Series.value_counts))

qd  gos  training2  creadit3
0  302  356        153       291
1  102   48        251       113

In [281]:
# input
x = dataset.iloc[:, [1,2,3,4,5,6,7,8]].values

# output
y = dataset.iloc[:,0].values

In [323]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.28, random_state = 0)

In [324]:
# from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# X_train = sc_x.fit_transform(X_train) 
# X_test = sc_x.transform(X_test)
  
print (X_train[0:10, :])

[[ 0.   1.   0.   2.   1.   5.  38.  12. ]
 [ 0.   0.   0.   2.   1.   1.  27.  10. ]
 [ 0.   0.   1.   1.   0.   5.  30.  12. ]
 [ 0.   0.   0.   2.   1.   6.  53.  12. ]
 [ 0.   1.   0.   1.   1.   2.  29.   2. ]
 [ 0.   1.   1.   7.   0.   3.  34.  20. ]
 [ 1.   0.   1.   6.   1.   3.  31.  12. ]
 [ 1.   0.   0.   8.   0.  10.  50.  13. ]
 [ 1.   1.   0.   4.   1.   6.  42.  18. ]
 [ 0.   1.   0.   9.5  0.   5.  35.   5. ]]


In [325]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [326]:
classifier.score(X_train, y_train)

0.7758620689655172

In [327]:
classifier.score(X_test, y_test)

0.7631578947368421

In [328]:
classifier.coef_

array([[ 0.86248739,  0.87169241,  0.59191896,  0.06146122,  0.23955602,
         0.21863187, -0.04753693,  0.05349269]])

In [329]:
y_pred = classifier.predict(X_test)

In [330]:
from sklearn.metrics import confusion_matrix
qd = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", qd)

Confusion Matrix : 
 [[81  4]
 [23  6]]


In [331]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.7631578947368421


In [334]:
classifier.predict(qd1.iloc[:, [1,2,3,4,5,6,7,8]].values)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,